### ISSUE TITLE
Entrega individual no Moodle

### ISSUE THREAD

**Issue by cauetcherfan** [kakateu/vpl7#3]
Entrega do VPL07 na plataforma 

- [x] entrega João.
- [x] entrega Matheus.
- [x] Entrega Cauet.

@joao-v-gomes @kakateu @cauetcherfan

**Comment by cauetcherfan** [comment]
Prazo: terça-feira (01/11)

**Comment by joao-v-gomes** [comment]
O prazo foi alterado para quinta (03/11).

Hoje eu já realizei a minha entrega.

**Comment by cauetcherfan** [comment]
Feito!
